//This file Take Markdown generated by the AI and convert it into something that looks nice in your terminal.
//marked is a Markdown parser.Markdown->marked->parsed output
//marked-terminal tells marked:format it for a terminal

import {marked} from "marked";
// @ts-ignore
import {markedTerminal} from "marked-terminal";

let ready=false;

// configure marked
function ensuredMarked():void{
    if(ready) return;
    //process.stdout.columns tells us roughly how many columns/characters wide the terminal currently is.
    //orDon't allow the width to become greater than 120
    const w=Math.max(40,Math.min(process.stdout.columns||80,120))

    //markedTerminal(...) creates a configuration/plugin that tells marked: to render markdown in terminal
    marked.use(markedTerminal({width:w,reflowText:true},{}));
    ready=true;
}

 export function renderTerminalMarkdown(source:string):string{
    ensuredMarked();
return marked.parse(source.trimEnd(),{async:false})
 }